title: "Dun's Mail Exchanger"
description: 'Семейный почтовый обменник.'

defaults:
  - scope:
      path: ''
    values:
      image: ''

webmaster_verifications:
  google: ''
  yandex: ''

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
